[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "17.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dcos/dcos-go"

[[constraint]]
  branch = "karl/swagger"
  name = "github.com/dcos/dcos-log"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.07"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[prune]
  go-tests = true
  unused-packages = true